config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :events do
    member do
      post :invite # custom route for inviting users
    end
    resources :event_attendees, only: [ :create, :destroy ]
  end
  resources :users
  resources :event_invitees, only: [] do
    member do
      patch :accept
      patch :decline
    end
  end

  get "invitations", to: "users#invitation"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

   # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
   # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
   # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

   # Defines the root path route ("/")
   root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User", foreign_key: "user_id"
  has_many :event_attendees, foreign_key: :attended_event_id
  has_many :attendees, through: :event_attendees, source: :attendee
  has_many :event_invitees, dependent: :destroy
  has_many :invitees, through: :event_invitees, source: :user

  # def self.past
  #   self.where(date: ..Date.today)
  # end

  # def self.future
  #   self.where(date: Date.today..)
  # end

  scope :past, -> { where(date: ..Date.today) }
  scope :future, -> { where(date: Date.today..) }
end

app/models/event_attendee.rb
class EventAttendee < ApplicationRecord
  belongs_to :attendee, class_name: "User"
  belongs_to :attended_event, class_name: "Event"
end

app/models/event_invitee.rb
class EventInvitee < ApplicationRecord
  belongs_to :event
  belongs_to :user

  enum :status, { pending: 0, accepted: 1, declined: 2 }
  validates :status, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :events, dependent: :destroy
  has_many :event_attendees, foreign_key: :attendee_id
  has_many :attended_events, through: :event_attendees, source: :attended_event
  has_many :event_invitees, dependent: :destroy
  has_many :invited_events, through: :event_invitees, source: :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  before_action :configure_permitted_parameters, if: :devise_controller?
  allow_browser versions: :modern


  protected

  def configure_permitted_parameters
    # Permit the `name` parameter for sign-up and account updates
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :name ])
    devise_parameter_sanitizer.permit(:account_update, keys: [ :name ])
  end
end

app/controllers/event_attendees_controller.rb
class EventAttendeesController < ApplicationController
  before_action :authenticate_user!

  def create
    @event = Event.find(params[:event_id])

    if @event.attendees.include?(current_user)
      redirect_to @event, alert: "you are already attending this event"
    else
      @event_attendee = EventAttendee.create(attended_event: @event, attendee: current_user)

      if @event_attendee.persisted?
        redirect_to @event, notice: "You have successfully attended the event"
      else
        redirect_to @event, notice: "something went wrong, try again"
      end
    end
  end

  def destroy
    @event = Event.find(params[:event_id])
    @event_attendee = EventAttendee.find_by(attended_event: @event, attendee: current_user)

    if @event_attendee
      @event_attendee.destroy
      redirect_to @event, notice: "you have successfully left the event"
    else
      redirect_to @event, alert: "you are not attending this event"
    end
  end
end

app/controllers/event_invitees_controller.rb
class EventInviteesController < ApplicationController
  before_action :set_invite, only: %i[accept decline]

  def accept
    @invite.accepted!
    redirect_to invitations_path, notice: "Invitation accepted."
  end

  def decline
     @invite.declined!  # Uses enum method
    redirect_to invitations_path, notice: "Invitation declined."
  end

  private

  def set_invite
    @invite = current_user.event_invitees.find(params[:id])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [ :new, :create ]
  def index
    @events = Event.all
  end

  def new
    @event = current_user.events.build
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = current_user.events.find(params[:id])
    if @event.update(event_params)
      redirect_to root_path, notice: "Event updated successfully"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def show
    puts "current_user: #{current_user.inspect}" # Debugging line
    @event = Event.find(params[:id])

    unless @event.invitees.include?(current_user) || @event.creator == current_user
      redirect_to root_path, alert: "you are not invited to this event"
    end
  end

  def destroy
    @event = current_user.events.find_by(id: params[:id])
    if @event
      @event.destroy
      redirect_to root_path, notice: "Event deleted successfully"
    else
      redirect_to root_path, alert: "Event not found or not authorized to delete."
    end
  end

  def invite
    @event = Event.find(params[:id])
    user = User.find_by(email: params[:email])
    puts "params[:email]: #{params[:email].inspect}"

    if user
      @event.event_invitees.create(user: user)
      redirect_to @event, notice: "User Invited Successfully"
    else
      redirect_to @event, alert: "User not found or already invited"
    end
  end

  private

  def event_params
    params.expect(event: [ :title, :date, :location ])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end

  def invitation
    @invitations = current_user.event_invitees.pending
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendees_helper.rb
module EventAttendeesHelper
end

app/helpers/event_invitees_helper.rb
module EventInviteesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event.html.erb
<p> Event is taking place on <%= event.date %> and the location is <%= event.location %></p>

app/views/events/_event_details.html.erb
<p> Event is taking place on <%= event.date %> and the location is <%= event.location %></p>

app/views/events/_form.html.erb
<div class="container">

<%= form_with model: event do |f| %>
    <div>
        <%= f.label :title %>
        <%= f.text_field :title %>
    </div>
    <div>
        <%= f.label :date %>
        <%= f.date_field  :date %>
    </div>
    <div>
        <%= f.label :location %>
        <%= f.text_field :location%>
    </div>
    <div>
        <%= f.submit%>
    </div>
<% end %>
</div>

app/views/events/edit.html.erb
<%= render partial: "events/form", locals: {event: @event} %>

app/views/events/index.html.erb
<ul>
    <% @events.each do |event| %>    
            <%= render partial: "shared/event", object: event %>
    <% end %>
</ul>

app/views/events/new.html.erb
<%= render partial: "events/form", locals: {event: @event} %>

app/views/events/show.html.erb
<h3>Event Details</h3>
<%# use locals since partials name doesn't match the object %>
<%= render partial: "events/event_details", locals: {event: @event}%>
<% if user_signed_in? %>
    <% if @event.attendees.include?(current_user) %>
        <%= link_to 'Leave Event', event_event_attendee_path(@event, current_user), data: { turbo_method: :delete}, class: "btn btn-danger" %>
    <% else %>
        <%= link_to "Attend Event", event_event_attendees_path(@event), data: { turbo_method: :post }, class: "btn btn-primary" %>
    <% end %>
<ul>
    <% if @event.attendees.any? %>
        <h6>people attending this event</h4>
        <% @event.attendees.each do |attendee|%>
            <li> <%= attendee.name %> </li>
        <% end %>
    <% else %>
        <h6> no one has signed up for this event yet</h6>
    <% end %>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Private Events" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>

    <% if notice %>
      <div class="alert alert-success">
        <%= notice %>
      </div>
    <% elsif alert %>
      <div class="alert alert-danger">
        <%= alert %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_event.html.erb
<li>
    <h4> <%= event.title%> </h4>
    <p>created by <%= event.creator.name%></p>
    <h5> <%= link_to "Details", event_path(event), class: "link" %> </h5>
    <% if event.creator == current_user %>

            <%= form_with url: invite_event_path(event), method: :post do |form| %>
                <%= form.label :email, "Invite a user by email" %>
                <%= form.email_field :email, required: true %>
                <%= form.submit "Send Invitation" %>
            <% end %>

        <h5> <%= link_to "Edit", edit_event_path(event), class: "link" %> </h5>
        <h5> <%= link_to "Delete", event_path(event), class: "link", data: { turbo_confirm: "are you sure yu want to delete this event?", turbo_method: :delete}, class: "btn btn-danger" %> </h5>
    <% end %>
</li>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "My Events", user_signed_in? ? user_path(current_user[:id]) : user_session_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
              <%= link_to "Home", root_path, class:"nav-link active"%>
        </li>
        <li class="nav-item">
              <%= link_to "Invitations", invitations_path, class:"nav-link active"%>
        </li>
        <li class="nav-item">
          <li> <%= link_to "Create Event", new_event_path, class:"nav-link active" %> </li>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            User
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Sign In", user_session_path, class: "dropdown-item" %>
            <%= link_to "Sign Up", new_user_registration_path, class: "dropdown-item" %>
            <li><hr class="dropdown-divider"></li>
            <%= link_to "Sign Out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
          </ul>
        </li>
        
      </ul>
    </div>
  </div>
</nav>

app/views/users/invitation.html.erb
<% if @invitations.pending.any? %>
<h2>Pending Invitations</h2>
<ul>
     <% @invitations.each do |invite| %>
    <li>
      <%= invite.event.title %>
      <%= link_to "Accept", accept_event_invitee_path(invite), data: { turbo_method: :patch} %>
      <%= link_to "Decline", decline_event_invitee_path(invite), data: {turbo_method: :patch}%>
    </li>
  <% end %>
</ul>
<% else %>
<h2>No Invites</h2>
<% end %>

app/views/users/show.html.erb
<h3> My Events </h3>
<ul> 
    <% current_user.events.all.each do |event| %>
        <%= render partial: "shared/event", object: event %>
    <% end %>
</ul>

<h3> Past Events </h3>
<ul>
    <% current_user.attended_events.past.each do |event|%>
        <%= render partial: "shared/event", object: event %>
    <% end %>
</ul>

<h3> Upcoming Events </h3>
<ul>
    <% current_user.attended_events.future.each do |event|%>
        <%= render partial: "shared/event", object: event %>
    <% end %>
</ul>